global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "n8n"
    static_configs:
      - targets: ["192.168.22.146:5678"]
